// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#ifndef UI_SCREEN9_H
#define UI_SCREEN9_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen9
extern void ui_Screen9_screen_init(void);
extern void ui_Screen9_screen_destroy(void);
extern void ui_event_Screen9(lv_event_t * e);
extern lv_obj_t * ui_Screen9;
extern lv_obj_t * ui_addUsrPnl1;
extern lv_obj_t * ui_UsrPnl1;
extern lv_obj_t * ui_wifiSSIDTxt;
extern lv_obj_t * ui_wifiPswdTxt;
extern void ui_event_wifiSSIDBx(lv_event_t * e);
extern lv_obj_t * ui_wifiSSIDBx;
extern void ui_event_wifiPswdBx(lv_event_t * e);
extern lv_obj_t * ui_wifiPswdBx;
extern void ui_event_wifiSbmtBtn(lv_event_t * e);
extern lv_obj_t * ui_wifiSbmtBtn;
extern lv_obj_t * ui_wifiSbmtBtnTxt;
extern void ui_event_wifiCancelBtn1(lv_event_t * e);
extern lv_obj_t * ui_wifiCancelBtn1;
extern lv_obj_t * ui_wifiCancelBtnTxt;
extern lv_obj_t * ui_Kbrd1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

