// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_addUsrPnl;
extern lv_obj_t * ui_UsrPnl;
extern lv_obj_t * ui_BxEmptyMsg;
extern lv_obj_t * ui_invldIpMsg;
extern lv_obj_t * ui_lengthMsg;
extern lv_obj_t * ui_usrExstMsg;
extern lv_obj_t * ui_usrNm1;
extern lv_obj_t * ui_pswd1;
extern void ui_event_usrNmBx(lv_event_t * e);
extern lv_obj_t * ui_usrNmBx;
extern void ui_event_pswdBx(lv_event_t * e);
extern lv_obj_t * ui_pswdBx;
extern void ui_event_sbmtBtn(lv_event_t * e);
extern lv_obj_t * ui_sbmtBtn;
extern lv_obj_t * ui_sbmtBtnTxt;
extern void ui_event_cancelBtn(lv_event_t * e);
extern lv_obj_t * ui_cancelBtn;
extern lv_obj_t * ui_cancelBtnTxt;
extern lv_obj_t * ui_Kbrd;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

