// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#include "../ui.h"

lv_obj_t * ui_Screen9 = NULL;
lv_obj_t * ui_addUsrPnl1 = NULL;
lv_obj_t * ui_UsrPnl1 = NULL;
lv_obj_t * ui_wifiSSIDTxt = NULL;
lv_obj_t * ui_wifiPswdTxt = NULL;
lv_obj_t * ui_wifiSSIDBx = NULL;
lv_obj_t * ui_wifiPswdBx = NULL;
lv_obj_t * ui_wifiSbmtBtn = NULL;
lv_obj_t * ui_wifiSbmtBtnTxt = NULL;
lv_obj_t * ui_wifiCancelBtn1 = NULL;
lv_obj_t * ui_wifiCancelBtnTxt = NULL;
lv_obj_t * ui_Kbrd1 = NULL;
// event funtions
void ui_event_Screen9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Kbrd1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_wifiSSIDBx, LV_STATE_PRESSED, _UI_MODIFY_STATE_REMOVE);
        _ui_basic_set_property(ui_addUsrPnl1, _UI_BASIC_PROPERTY_POSITION_Y,  -30);
        _ui_state_modify(ui_wifiPswdBx, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_wifiSSIDBx, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_wifiSSIDBx(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Kbrd1,  ui_wifiSSIDBx);
        _ui_flag_modify(ui_Kbrd1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_addUsrPnl1, _UI_BASIC_PROPERTY_POSITION_Y,  -80);
    }
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Kbrd1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_wifiSSIDBx, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        _ui_basic_set_property(ui_addUsrPnl1, _UI_BASIC_PROPERTY_POSITION_Y,  -30);
    }
}

void ui_event_wifiPswdBx(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Kbrd1,  ui_wifiPswdBx);
        _ui_flag_modify(ui_Kbrd1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_addUsrPnl1, _UI_BASIC_PROPERTY_POSITION_Y,  -100);
    }
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Kbrd1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_Screen9, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_wifiPswdBx, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        _ui_basic_set_property(ui_addUsrPnl1, _UI_BASIC_PROPERTY_POSITION_Y,  -30);
    }
}

void ui_event_wifiSbmtBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen6_screen_init);
        wifi_cnfg(e);
    }
}

void ui_event_wifiCancelBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
        clr_textArea(e);
    }
}

// build funtions

void ui_Screen9_screen_init(void)
{
    ui_Screen9 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Screen9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_addUsrPnl1 = lv_obj_create(ui_Screen9);
    lv_obj_set_width(ui_addUsrPnl1, 692);
    lv_obj_set_height(ui_addUsrPnl1, 400);
    lv_obj_set_x(ui_addUsrPnl1, 0);
    lv_obj_set_y(ui_addUsrPnl1, -30);
    lv_obj_set_align(ui_addUsrPnl1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_addUsrPnl1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_addUsrPnl1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_addUsrPnl1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);
    ui_object_set_themeable_style_property(ui_addUsrPnl1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_addUsrPnl1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_border_width(ui_addUsrPnl1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UsrPnl1 = lv_obj_create(ui_addUsrPnl1);
    lv_obj_set_width(ui_UsrPnl1, 512);
    lv_obj_set_height(ui_UsrPnl1, 240);
    lv_obj_set_align(ui_UsrPnl1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_UsrPnl1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_UsrPnl1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color3);
    ui_object_set_themeable_style_property(ui_UsrPnl1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color3);
    lv_obj_set_style_border_width(ui_UsrPnl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiSSIDTxt = lv_label_create(ui_UsrPnl1);
    lv_obj_set_width(ui_wifiSSIDTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiSSIDTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiSSIDTxt, 0);
    lv_obj_set_y(ui_wifiSSIDTxt, -35);
    lv_obj_set_align(ui_wifiSSIDTxt, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_wifiSSIDTxt, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wifiSSIDTxt, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_wifiSSIDTxt, "SSID:");

    ui_wifiPswdTxt = lv_label_create(ui_UsrPnl1);
    lv_obj_set_width(ui_wifiPswdTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiPswdTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiPswdTxt, 0);
    lv_obj_set_y(ui_wifiPswdTxt, 25);
    lv_obj_set_align(ui_wifiPswdTxt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_wifiPswdTxt, "Password:\n");

    ui_wifiSSIDBx = lv_textarea_create(ui_UsrPnl1);
    lv_obj_set_width(ui_wifiSSIDBx, 303);
    lv_obj_set_height(ui_wifiSSIDBx, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_wifiSSIDBx, 90);
    lv_obj_set_y(ui_wifiSSIDBx, -35);
    lv_obj_set_align(ui_wifiSSIDBx, LV_ALIGN_LEFT_MID);
    lv_textarea_set_max_length(ui_wifiSSIDBx, 8);
    lv_textarea_set_placeholder_text(ui_wifiSSIDBx, "name@123");
    lv_textarea_set_one_line(ui_wifiSSIDBx, true);

    ui_wifiPswdBx = lv_textarea_create(ui_UsrPnl1);
    lv_obj_set_width(ui_wifiPswdBx, 303);
    lv_obj_set_height(ui_wifiPswdBx, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_wifiPswdBx, 90);
    lv_obj_set_y(ui_wifiPswdBx, 20);
    lv_obj_set_align(ui_wifiPswdBx, LV_ALIGN_LEFT_MID);
    lv_textarea_set_max_length(ui_wifiPswdBx, 20);
    lv_textarea_set_placeholder_text(ui_wifiPswdBx, "abc@#!*123");
    lv_textarea_set_one_line(ui_wifiPswdBx, true);

    ui_wifiSbmtBtn = lv_btn_create(ui_UsrPnl1);
    lv_obj_set_width(ui_wifiSbmtBtn, 100);
    lv_obj_set_height(ui_wifiSbmtBtn, 40);
    lv_obj_set_x(ui_wifiSbmtBtn, -60);
    lv_obj_set_y(ui_wifiSbmtBtn, 0);
    lv_obj_set_align(ui_wifiSbmtBtn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_wifiSbmtBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiSbmtBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_wifiSbmtBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color4);
    ui_object_set_themeable_style_property(ui_wifiSbmtBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color4);

    ui_wifiSbmtBtnTxt = lv_label_create(ui_wifiSbmtBtn);
    lv_obj_set_width(ui_wifiSbmtBtnTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiSbmtBtnTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifiSbmtBtnTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiSbmtBtnTxt, "Submit");
    ui_object_set_themeable_style_property(ui_wifiSbmtBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_wifiSbmtBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);

    ui_wifiCancelBtn1 = lv_btn_create(ui_UsrPnl1);
    lv_obj_set_width(ui_wifiCancelBtn1, 100);
    lv_obj_set_height(ui_wifiCancelBtn1, 40);
    lv_obj_set_x(ui_wifiCancelBtn1, 60);
    lv_obj_set_y(ui_wifiCancelBtn1, 0);
    lv_obj_set_align(ui_wifiCancelBtn1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_wifiCancelBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiCancelBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_wifiCancelBtn1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color4);
    ui_object_set_themeable_style_property(ui_wifiCancelBtn1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color4);

    ui_wifiCancelBtnTxt = lv_label_create(ui_wifiCancelBtn1);
    lv_obj_set_width(ui_wifiCancelBtnTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiCancelBtnTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifiCancelBtnTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiCancelBtnTxt, "Cancel");
    ui_object_set_themeable_style_property(ui_wifiCancelBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_wifiCancelBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);

    ui_Kbrd1 = lv_keyboard_create(ui_Screen9);
    lv_obj_set_width(ui_Kbrd1, 800);
    lv_obj_set_height(ui_Kbrd1, 259);
    lv_obj_set_align(ui_Kbrd1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Kbrd1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_set_style_bg_color(ui_Kbrd1, lv_color_hex(0xD5EEFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Kbrd1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_wifiSSIDBx, ui_event_wifiSSIDBx, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiPswdBx, ui_event_wifiPswdBx, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiSbmtBtn, ui_event_wifiSbmtBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiCancelBtn1, ui_event_wifiCancelBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen9, ui_event_Screen9, LV_EVENT_ALL, NULL);

}

void ui_Screen9_screen_destroy(void)
{
    if(ui_Screen9) lv_obj_del(ui_Screen9);

    // NULL screen variables
    ui_Screen9 = NULL;
    ui_addUsrPnl1 = NULL;
    ui_UsrPnl1 = NULL;
    ui_wifiSSIDTxt = NULL;
    ui_wifiPswdTxt = NULL;
    ui_wifiSSIDBx = NULL;
    ui_wifiPswdBx = NULL;
    ui_wifiSbmtBtn = NULL;
    ui_wifiSbmtBtnTxt = NULL;
    ui_wifiCancelBtn1 = NULL;
    ui_wifiCancelBtnTxt = NULL;
    ui_Kbrd1 = NULL;

}
