// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#include "../ui.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_sbmtPnl = NULL;
lv_obj_t * ui_bckSbmtBtn = NULL;
lv_obj_t * ui_bckSbmtBtnTxt = NULL;
lv_obj_t * ui_sbmtTxtPnl = NULL;
lv_obj_t * ui_sbmtTxt = NULL;
lv_obj_t * ui_Image2 = NULL;
// event funtions
void ui_event_Screen6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_sbmtPnl, _UI_BASIC_PROPERTY_POSITION_Y,  -30);
    }
}

void ui_event_bckSbmtBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Screen6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_sbmtPnl = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_sbmtPnl, 692);
    lv_obj_set_height(ui_sbmtPnl, 400);
    lv_obj_set_x(ui_sbmtPnl, 0);
    lv_obj_set_y(ui_sbmtPnl, -30);
    lv_obj_set_align(ui_sbmtPnl, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_sbmtPnl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_sbmtPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_sbmtPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);
    ui_object_set_themeable_style_property(ui_sbmtPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_sbmtPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_border_width(ui_sbmtPnl, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bckSbmtBtn = lv_btn_create(ui_sbmtPnl);
    lv_obj_set_width(ui_bckSbmtBtn, 100);
    lv_obj_set_height(ui_bckSbmtBtn, 33);
    lv_obj_set_align(ui_bckSbmtBtn, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_bckSbmtBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_bckSbmtBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_bckSbmtBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color4);
    ui_object_set_themeable_style_property(ui_bckSbmtBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color4);

    ui_bckSbmtBtnTxt = lv_label_create(ui_bckSbmtBtn);
    lv_obj_set_width(ui_bckSbmtBtnTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bckSbmtBtnTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bckSbmtBtnTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bckSbmtBtnTxt, "Back");
    ui_object_set_themeable_style_property(ui_bckSbmtBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_bckSbmtBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);

    ui_sbmtTxtPnl = lv_obj_create(ui_sbmtPnl);
    lv_obj_set_width(ui_sbmtTxtPnl, 300);
    lv_obj_set_height(ui_sbmtTxtPnl, 100);
    lv_obj_set_align(ui_sbmtTxtPnl, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sbmtTxtPnl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_sbmtTxtPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color4);
    ui_object_set_themeable_style_property(ui_sbmtTxtPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color4);
    lv_obj_set_style_border_width(ui_sbmtTxtPnl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sbmtTxt = lv_label_create(ui_sbmtTxtPnl);
    lv_obj_set_width(ui_sbmtTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sbmtTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sbmtTxt, -30);
    lv_obj_set_y(ui_sbmtTxt, 0);
    lv_obj_set_align(ui_sbmtTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sbmtTxt, "Submitted!");
    ui_object_set_themeable_style_property(ui_sbmtTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_sbmtTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_text_align(ui_sbmtTxt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sbmtTxt, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sbmtTxt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_sbmtTxtPnl);
    lv_img_set_src(ui_Image2, &ui_img_tick_png);
    lv_obj_set_width(ui_Image2, 50);
    lv_obj_set_height(ui_Image2, 50);
    lv_obj_set_x(ui_Image2, -18);
    lv_obj_set_y(ui_Image2, -2);
    lv_obj_set_align(ui_Image2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_bckSbmtBtn, ui_event_bckSbmtBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen6, ui_event_Screen6, LV_EVENT_ALL, NULL);

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_sbmtPnl = NULL;
    ui_bckSbmtBtn = NULL;
    ui_bckSbmtBtnTxt = NULL;
    ui_sbmtTxtPnl = NULL;
    ui_sbmtTxt = NULL;
    ui_Image2 = NULL;

}
