// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern void ui_event_Screen6(lv_event_t * e);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_sbmtPnl;
extern void ui_event_bckSbmtBtn(lv_event_t * e);
extern lv_obj_t * ui_bckSbmtBtn;
extern lv_obj_t * ui_bckSbmtBtnTxt;
extern lv_obj_t * ui_sbmtTxtPnl;
extern lv_obj_t * ui_sbmtTxt;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

