// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#include "../ui.h"

lv_obj_t * ui_Screen7 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_TmprLable = NULL;
lv_obj_t * ui_TmprValue = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_hmdtLable1 = NULL;
lv_obj_t * ui_hmdtValue1 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_hmdtLable2 = NULL;
lv_obj_t * ui_hmdtValue2 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_prsLable1 = NULL;
lv_obj_t * ui_prsValue1 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_prsLable2 = NULL;
lv_obj_t * ui_prsValue2 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_prsLable3 = NULL;
lv_obj_t * ui_prsValue3 = NULL;
lv_obj_t * ui_BckBtn = NULL;
lv_obj_t * ui_BckBtnTxt = NULL;
// event funtions
void ui_event_BckBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Screen7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Container3 = lv_obj_create(ui_Screen7);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 710);
    lv_obj_set_height(ui_Container3, 172);
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, 70);
    lv_obj_set_align(ui_Container3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel2, 213);
    lv_obj_set_height(ui_Panel2, 129);
    lv_obj_set_x(ui_Panel2, 20);
    lv_obj_set_y(ui_Panel2, 20);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color3);
    ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color3);
    ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_color5);
    lv_obj_set_style_bg_main_stop(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_color4);
    ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_color4);
    lv_obj_set_style_border_width(ui_Panel2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_shadow_width(ui_Panel2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TmprLable = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_TmprLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TmprLable, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_TmprLable, "Temperature 1 :");
    ui_object_set_themeable_style_property(ui_TmprLable, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_TmprLable, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_text_font(ui_TmprLable, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TmprValue = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_TmprValue, 200);
    lv_obj_set_height(ui_TmprValue, 15);
    lv_obj_set_align(ui_TmprValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TmprValue, "0");
    lv_obj_set_style_text_align(ui_TmprValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TmprValue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel1, 213);
    lv_obj_set_height(ui_Panel1, 129);
    lv_obj_set_x(ui_Panel1, 250);
    lv_obj_set_y(ui_Panel1, 20);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color3);
    ui_object_set_themeable_style_property(ui_Panel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color3);
    ui_object_set_themeable_style_property(ui_Panel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_color5);
    lv_obj_set_style_bg_main_stop(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Panel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Panel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_shadow_width(ui_Panel1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hmdtLable1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_hmdtLable1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hmdtLable1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_hmdtLable1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_hmdtLable1, "Humidity 1 :");
    ui_object_set_themeable_style_property(ui_hmdtLable1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_hmdtLable1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_text_font(ui_hmdtLable1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hmdtValue1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_hmdtValue1, 200);
    lv_obj_set_height(ui_hmdtValue1, 15);
    lv_obj_set_align(ui_hmdtValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hmdtValue1, "0");
    lv_obj_set_style_text_align(ui_hmdtValue1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hmdtValue1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel3, 213);
    lv_obj_set_height(ui_Panel3, 129);
    lv_obj_set_x(ui_Panel3, 480);
    lv_obj_set_y(ui_Panel3, 20);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color3);
    ui_object_set_themeable_style_property(ui_Panel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color3);
    ui_object_set_themeable_style_property(ui_Panel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_color5);
    lv_obj_set_style_bg_grad_dir(ui_Panel3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Panel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Panel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_shadow_width(ui_Panel3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hmdtLable2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_hmdtLable2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hmdtLable2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_hmdtLable2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_hmdtLable2, "Humidity 2 :");
    ui_object_set_themeable_style_property(ui_hmdtLable2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_hmdtLable2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_text_font(ui_hmdtLable2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hmdtValue2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_hmdtValue2, 200);
    lv_obj_set_height(ui_hmdtValue2, 15);
    lv_obj_set_align(ui_hmdtValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hmdtValue2, "0");
    lv_obj_set_style_text_align(ui_hmdtValue2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hmdtValue2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen7);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 710);
    lv_obj_set_height(ui_Container1, 172);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 250);
    lv_obj_set_align(ui_Container1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel4, 213);
    lv_obj_set_height(ui_Panel4, 129);
    lv_obj_set_x(ui_Panel4, 20);
    lv_obj_set_y(ui_Panel4, 20);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color3);
    ui_object_set_themeable_style_property(ui_Panel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color3);
    ui_object_set_themeable_style_property(ui_Panel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_color5);
    lv_obj_set_style_bg_grad_dir(ui_Panel4, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Panel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Panel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_shadow_width(ui_Panel4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_prsLable1 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_prsLable1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_prsLable1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_prsLable1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_prsLable1, "Pressure 1 :");
    ui_object_set_themeable_style_property(ui_prsLable1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_prsLable1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_text_align(ui_prsLable1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_prsLable1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_prsValue1 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_prsValue1, 200);
    lv_obj_set_height(ui_prsValue1, 15);
    lv_obj_set_align(ui_prsValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_prsValue1, "0");
    lv_obj_set_style_text_align(ui_prsValue1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_prsValue1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel5, 213);
    lv_obj_set_height(ui_Panel5, 129);
    lv_obj_set_x(ui_Panel5, 250);
    lv_obj_set_y(ui_Panel5, 20);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color3);
    ui_object_set_themeable_style_property(ui_Panel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color3);
    ui_object_set_themeable_style_property(ui_Panel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_color5);
    lv_obj_set_style_bg_grad_dir(ui_Panel5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Panel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Panel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_shadow_width(ui_Panel5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_prsLable2 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_prsLable2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_prsLable2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_prsLable2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_prsLable2, "Pressure 2 :");
    ui_object_set_themeable_style_property(ui_prsLable2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_prsLable2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_text_align(ui_prsLable2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_prsLable2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_prsValue2 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_prsValue2, 200);
    lv_obj_set_height(ui_prsValue2, 15);
    lv_obj_set_align(ui_prsValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_prsValue2, "0");
    lv_obj_set_style_text_align(ui_prsValue2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_prsValue2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel6, 213);
    lv_obj_set_height(ui_Panel6, 129);
    lv_obj_set_x(ui_Panel6, 480);
    lv_obj_set_y(ui_Panel6, 19);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color3);
    ui_object_set_themeable_style_property(ui_Panel6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color3);
    ui_object_set_themeable_style_property(ui_Panel6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_color5);
    lv_obj_set_style_bg_grad_dir(ui_Panel6, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Panel6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Panel6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_shadow_width(ui_Panel6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_prsLable3 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_prsLable3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_prsLable3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_prsLable3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_prsLable3, "Pressure 3 :");
    ui_object_set_themeable_style_property(ui_prsLable3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_prsLable3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_text_align(ui_prsLable3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_prsLable3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_prsValue3 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_prsValue3, 200);
    lv_obj_set_height(ui_prsValue3, 15);
    lv_obj_set_align(ui_prsValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_prsValue3, "0");
    lv_obj_set_style_text_align(ui_prsValue3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_prsValue3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BckBtn = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_BckBtn, 100);
    lv_obj_set_height(ui_BckBtn, 33);
    lv_obj_set_x(ui_BckBtn, 20);
    lv_obj_set_y(ui_BckBtn, 20);
    lv_obj_add_flag(ui_BckBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BckBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_BckBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color5);
    ui_object_set_themeable_style_property(ui_BckBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color5);

    ui_BckBtnTxt = lv_label_create(ui_BckBtn);
    lv_obj_set_width(ui_BckBtnTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BckBtnTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BckBtnTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BckBtnTxt, "Back");
    ui_object_set_themeable_style_property(ui_BckBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_BckBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);

    lv_obj_add_event_cb(ui_BckBtn, ui_event_BckBtn, LV_EVENT_ALL, NULL);

}

void ui_Screen7_screen_destroy(void)
{
    if(ui_Screen7) lv_obj_del(ui_Screen7);

    // NULL screen variables
    ui_Screen7 = NULL;
    ui_Container3 = NULL;
    ui_Panel2 = NULL;
    ui_TmprLable = NULL;
    ui_TmprValue = NULL;
    ui_Panel1 = NULL;
    ui_hmdtLable1 = NULL;
    ui_hmdtValue1 = NULL;
    ui_Panel3 = NULL;
    ui_hmdtLable2 = NULL;
    ui_hmdtValue2 = NULL;
    ui_Container1 = NULL;
    ui_Panel4 = NULL;
    ui_prsLable1 = NULL;
    ui_prsValue1 = NULL;
    ui_Panel5 = NULL;
    ui_prsLable2 = NULL;
    ui_prsValue2 = NULL;
    ui_Panel6 = NULL;
    ui_prsLable3 = NULL;
    ui_prsValue3 = NULL;
    ui_BckBtn = NULL;
    ui_BckBtnTxt = NULL;

}
