// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#include "../ui.h"

lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_addUsrPnl = NULL;
lv_obj_t * ui_UsrPnl = NULL;
lv_obj_t * ui_BxEmptyMsg = NULL;
lv_obj_t * ui_invldIpMsg = NULL;
lv_obj_t * ui_lengthMsg = NULL;
lv_obj_t * ui_usrExstMsg = NULL;
lv_obj_t * ui_usrNm1 = NULL;
lv_obj_t * ui_pswd1 = NULL;
lv_obj_t * ui_usrNmBx = NULL;
lv_obj_t * ui_pswdBx = NULL;
lv_obj_t * ui_sbmtBtn = NULL;
lv_obj_t * ui_sbmtBtnTxt = NULL;
lv_obj_t * ui_cancelBtn = NULL;
lv_obj_t * ui_cancelBtnTxt = NULL;
lv_obj_t * ui_Kbrd = NULL;
// event funtions
void ui_event_Screen5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Kbrd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_usrNmBx, LV_STATE_PRESSED, _UI_MODIFY_STATE_REMOVE);
        _ui_basic_set_property(ui_addUsrPnl, _UI_BASIC_PROPERTY_POSITION_Y,  -30);
        _ui_state_modify(ui_pswdBx, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_usrNmBx, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_usrNmBx(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Kbrd,  ui_usrNmBx);
        _ui_flag_modify(ui_Kbrd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_addUsrPnl, _UI_BASIC_PROPERTY_POSITION_Y,  -80);
        _ui_flag_modify(ui_BxEmptyMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_invldIpMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_lengthMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Kbrd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_usrNmBx, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        _ui_basic_set_property(ui_addUsrPnl, _UI_BASIC_PROPERTY_POSITION_Y,  -30);
    }
}

void ui_event_pswdBx(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Kbrd,  ui_pswdBx);
        _ui_flag_modify(ui_Kbrd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_addUsrPnl, _UI_BASIC_PROPERTY_POSITION_Y,  -100);
        _ui_flag_modify(ui_BxEmptyMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_invldIpMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_lengthMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Kbrd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_Screen5, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_pswdBx, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        _ui_basic_set_property(ui_addUsrPnl, _UI_BASIC_PROPERTY_POSITION_Y,  -30);
    }
}

void ui_event_sbmtBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        usr_config(e);
    }
}

void ui_event_cancelBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
        clr_textArea(e);
    }
}

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Screen5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_addUsrPnl = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_addUsrPnl, 692);
    lv_obj_set_height(ui_addUsrPnl, 400);
    lv_obj_set_x(ui_addUsrPnl, 0);
    lv_obj_set_y(ui_addUsrPnl, -30);
    lv_obj_set_align(ui_addUsrPnl, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_addUsrPnl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_addUsrPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_addUsrPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);
    ui_object_set_themeable_style_property(ui_addUsrPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_addUsrPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_border_width(ui_addUsrPnl, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UsrPnl = lv_obj_create(ui_addUsrPnl);
    lv_obj_set_width(ui_UsrPnl, 512);
    lv_obj_set_height(ui_UsrPnl, 240);
    lv_obj_set_align(ui_UsrPnl, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_UsrPnl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_UsrPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color3);
    ui_object_set_themeable_style_property(ui_UsrPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color3);
    lv_obj_set_style_border_width(ui_UsrPnl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BxEmptyMsg = lv_label_create(ui_UsrPnl);
    lv_obj_set_width(ui_BxEmptyMsg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BxEmptyMsg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BxEmptyMsg, 95);
    lv_obj_set_y(ui_BxEmptyMsg, 25);
    lv_label_set_text(ui_BxEmptyMsg, "Error: Cannot give empty");
    lv_obj_add_flag(ui_BxEmptyMsg, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_BxEmptyMsg, lv_color_hex(0xE7081A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BxEmptyMsg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BxEmptyMsg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_invldIpMsg = lv_label_create(ui_UsrPnl);
    lv_obj_set_width(ui_invldIpMsg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_invldIpMsg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_invldIpMsg, 95);
    lv_obj_set_y(ui_invldIpMsg, 25);
    lv_label_set_text(ui_invldIpMsg, "Error: Invalid input");
    lv_obj_add_flag(ui_invldIpMsg, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_invldIpMsg, lv_color_hex(0xE7081A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_invldIpMsg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_invldIpMsg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lengthMsg = lv_label_create(ui_UsrPnl);
    lv_obj_set_width(ui_lengthMsg, 314);
    lv_obj_set_height(ui_lengthMsg, 18);
    lv_obj_set_x(ui_lengthMsg, 95);
    lv_obj_set_y(ui_lengthMsg, 25);
    lv_label_set_text(ui_lengthMsg, "Error: Please give ID longer then 4 digits");
    lv_obj_add_flag(ui_lengthMsg, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_lengthMsg, lv_color_hex(0xE7081A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lengthMsg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lengthMsg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_usrExstMsg = lv_label_create(ui_UsrPnl);
    lv_obj_set_width(ui_usrExstMsg, 275);
    lv_obj_set_height(ui_usrExstMsg, 18);
    lv_obj_set_x(ui_usrExstMsg, 95);
    lv_obj_set_y(ui_usrExstMsg, 25);
    lv_label_set_text(ui_usrExstMsg, "Error: User already exists");
    lv_obj_add_flag(ui_usrExstMsg, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_usrExstMsg, lv_color_hex(0xE7081A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_usrExstMsg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_usrExstMsg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_usrNm1 = lv_label_create(ui_UsrPnl);
    lv_obj_set_width(ui_usrNm1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_usrNm1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_usrNm1, 0);
    lv_obj_set_y(ui_usrNm1, -35);
    lv_obj_set_align(ui_usrNm1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_usrNm1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_usrNm1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_usrNm1, "User ID:");

    ui_pswd1 = lv_label_create(ui_UsrPnl);
    lv_obj_set_width(ui_pswd1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pswd1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pswd1, 0);
    lv_obj_set_y(ui_pswd1, 25);
    lv_obj_set_align(ui_pswd1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_pswd1, "Password:\n");

    ui_usrNmBx = lv_textarea_create(ui_UsrPnl);
    lv_obj_set_width(ui_usrNmBx, 303);
    lv_obj_set_height(ui_usrNmBx, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_usrNmBx, 90);
    lv_obj_set_y(ui_usrNmBx, -35);
    lv_obj_set_align(ui_usrNmBx, LV_ALIGN_LEFT_MID);
    lv_textarea_set_max_length(ui_usrNmBx, 8);
    lv_textarea_set_placeholder_text(ui_usrNmBx, "1234567890");
    lv_textarea_set_one_line(ui_usrNmBx, true);

    ui_pswdBx = lv_textarea_create(ui_UsrPnl);
    lv_obj_set_width(ui_pswdBx, 303);
    lv_obj_set_height(ui_pswdBx, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_pswdBx, 90);
    lv_obj_set_y(ui_pswdBx, 20);
    lv_obj_set_align(ui_pswdBx, LV_ALIGN_LEFT_MID);
    lv_textarea_set_max_length(ui_pswdBx, 4);
    lv_textarea_set_placeholder_text(ui_pswdBx, "( 4 digit pin )");
    lv_textarea_set_one_line(ui_pswdBx, true);

    ui_sbmtBtn = lv_btn_create(ui_UsrPnl);
    lv_obj_set_width(ui_sbmtBtn, 100);
    lv_obj_set_height(ui_sbmtBtn, 40);
    lv_obj_set_x(ui_sbmtBtn, -60);
    lv_obj_set_y(ui_sbmtBtn, 0);
    lv_obj_set_align(ui_sbmtBtn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_sbmtBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sbmtBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_sbmtBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color4);
    ui_object_set_themeable_style_property(ui_sbmtBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color4);

    ui_sbmtBtnTxt = lv_label_create(ui_sbmtBtn);
    lv_obj_set_width(ui_sbmtBtnTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sbmtBtnTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_sbmtBtnTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sbmtBtnTxt, "Submit");
    ui_object_set_themeable_style_property(ui_sbmtBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_sbmtBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);

    ui_cancelBtn = lv_btn_create(ui_UsrPnl);
    lv_obj_set_width(ui_cancelBtn, 100);
    lv_obj_set_height(ui_cancelBtn, 40);
    lv_obj_set_x(ui_cancelBtn, 60);
    lv_obj_set_y(ui_cancelBtn, 0);
    lv_obj_set_align(ui_cancelBtn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_cancelBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_cancelBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_cancelBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color4);
    ui_object_set_themeable_style_property(ui_cancelBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color4);

    ui_cancelBtnTxt = lv_label_create(ui_cancelBtn);
    lv_obj_set_width(ui_cancelBtnTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cancelBtnTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_cancelBtnTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cancelBtnTxt, "Cancel");
    ui_object_set_themeable_style_property(ui_cancelBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_cancelBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);

    ui_Kbrd = lv_keyboard_create(ui_Screen5);
    lv_keyboard_set_mode(ui_Kbrd, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Kbrd, 800);
    lv_obj_set_height(ui_Kbrd, 259);
    lv_obj_set_align(ui_Kbrd, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Kbrd, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_set_style_bg_color(ui_Kbrd, lv_color_hex(0xD5EEFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Kbrd, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_usrNmBx, ui_event_usrNmBx, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pswdBx, ui_event_pswdBx, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sbmtBtn, ui_event_sbmtBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cancelBtn, ui_event_cancelBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen5, ui_event_Screen5, LV_EVENT_ALL, NULL);

}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_addUsrPnl = NULL;
    ui_UsrPnl = NULL;
    ui_BxEmptyMsg = NULL;
    ui_invldIpMsg = NULL;
    ui_lengthMsg = NULL;
    ui_usrExstMsg = NULL;
    ui_usrNm1 = NULL;
    ui_pswd1 = NULL;
    ui_usrNmBx = NULL;
    ui_pswdBx = NULL;
    ui_sbmtBtn = NULL;
    ui_sbmtBtnTxt = NULL;
    ui_cancelBtn = NULL;
    ui_cancelBtnTxt = NULL;
    ui_Kbrd = NULL;

}
