// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#ifndef UI_SCREEN8_H
#define UI_SCREEN8_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen8
extern void ui_Screen8_screen_init(void);
extern void ui_Screen8_screen_destroy(void);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_errorMsg;
extern void ui_event_lgnUsrnm(lv_event_t * e);
extern lv_obj_t * ui_lgnUsrnm;
extern void ui_event_lgnPswd(lv_event_t * e);
extern lv_obj_t * ui_lgnPswd;
extern void ui_event_lginSbmtBtn(lv_event_t * e);
extern lv_obj_t * ui_lginSbmtBtn;
extern lv_obj_t * ui_lgnSbmtTxt;
extern void ui_event_lgnKbrd(lv_event_t * e);
extern lv_obj_t * ui_lgnKbrd;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

