// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_settingPnl2 = NULL;
lv_obj_t * ui_opListBtn1 = NULL;
lv_obj_t * ui_opListTxt1 = NULL;
lv_obj_t * ui_addUsrBtn1 = NULL;
lv_obj_t * ui_addUsrTxt1 = NULL;
lv_obj_t * ui_wifiCnfgbtn = NULL;
lv_obj_t * ui_wifiCnfgTxt = NULL;
lv_obj_t * ui_aboutBtn = NULL;
lv_obj_t * ui_aboutBtnTxt = NULL;
lv_obj_t * ui_settingCloseBtn = NULL;
lv_obj_t * ui_settingBtn = NULL;
lv_obj_t * ui_MachineBtn = NULL;
lv_obj_t * ui_machineBtnIcn = NULL;
lv_obj_t * ui_machineBtnTxt = NULL;
// event funtions
void ui_event_opListBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_addUsrBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_wifiCnfgbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen9, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen9_screen_init);
    }
}

void ui_event_aboutBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_settingCloseBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        settingClosePnl_Animation(ui_settingPnl2, 0);
        settingClsOrgn_Animation(ui_settingCloseBtn, 0);
        settingClsOrgn_Animation(ui_settingBtn, 0);
        _ui_flag_modify(ui_settingBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_settingBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        settingPnl_Animation(ui_settingPnl2, 0);
        _ui_flag_modify(ui_settingBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        stettingPnlStngClsBtn_Animation(ui_settingCloseBtn, 0);
        stettingPnlStngClsBtn_Animation(ui_settingBtn, 0);
    }
}

void ui_event_MachineBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen7_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Screen2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_settingPnl2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_settingPnl2, 50);
    lv_obj_set_height(ui_settingPnl2, 50);
    lv_obj_set_x(ui_settingPnl2, -50);
    lv_obj_set_y(ui_settingPnl2, 20);
    lv_obj_set_align(ui_settingPnl2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_settingPnl2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_settingPnl2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_settingPnl2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);
    ui_object_set_themeable_style_property(ui_settingPnl2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_settingPnl2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_border_width(ui_settingPnl2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_opListBtn1 = lv_btn_create(ui_settingPnl2);
    lv_obj_set_width(ui_opListBtn1, 160);
    lv_obj_set_height(ui_opListBtn1, 46);
    lv_obj_set_x(ui_opListBtn1, 0);
    lv_obj_set_y(ui_opListBtn1, 40);
    lv_obj_add_flag(ui_opListBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_opListBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_opListBtn1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color4);
    ui_object_set_themeable_style_property(ui_opListBtn1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color4);

    ui_opListTxt1 = lv_label_create(ui_opListBtn1);
    lv_obj_set_width(ui_opListTxt1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_opListTxt1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_opListTxt1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_opListTxt1, "Operator List");
    ui_object_set_themeable_style_property(ui_opListTxt1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_opListTxt1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);

    ui_addUsrBtn1 = lv_btn_create(ui_settingPnl2);
    lv_obj_set_width(ui_addUsrBtn1, 160);
    lv_obj_set_height(ui_addUsrBtn1, 46);
    lv_obj_set_x(ui_addUsrBtn1, 0);
    lv_obj_set_y(ui_addUsrBtn1, 100);
    lv_obj_add_flag(ui_addUsrBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_addUsrBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_addUsrBtn1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color4);
    ui_object_set_themeable_style_property(ui_addUsrBtn1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color4);

    ui_addUsrTxt1 = lv_label_create(ui_addUsrBtn1);
    lv_obj_set_width(ui_addUsrTxt1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_addUsrTxt1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_addUsrTxt1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_addUsrTxt1, "Add User");
    ui_object_set_themeable_style_property(ui_addUsrTxt1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_addUsrTxt1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);

    ui_wifiCnfgbtn = lv_btn_create(ui_settingPnl2);
    lv_obj_set_width(ui_wifiCnfgbtn, 160);
    lv_obj_set_height(ui_wifiCnfgbtn, 47);
    lv_obj_set_x(ui_wifiCnfgbtn, 0);
    lv_obj_set_y(ui_wifiCnfgbtn, 159);
    lv_obj_add_flag(ui_wifiCnfgbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiCnfgbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_wifiCnfgbtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color4);
    ui_object_set_themeable_style_property(ui_wifiCnfgbtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color4);

    ui_wifiCnfgTxt = lv_label_create(ui_wifiCnfgbtn);
    lv_obj_set_width(ui_wifiCnfgTxt, 79);
    lv_obj_set_height(ui_wifiCnfgTxt, 26);
    lv_obj_set_align(ui_wifiCnfgTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiCnfgTxt, "WIFI credentials\n");
    ui_object_set_themeable_style_property(ui_wifiCnfgTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_wifiCnfgTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_text_align(ui_wifiCnfgTxt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_wifiCnfgTxt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_wifiCnfgTxt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_wifiCnfgTxt, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_wifiCnfgTxt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_wifiCnfgTxt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_wifiCnfgTxt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aboutBtn = lv_btn_create(ui_settingPnl2);
    lv_obj_set_width(ui_aboutBtn, 160);
    lv_obj_set_height(ui_aboutBtn, 46);
    lv_obj_set_x(ui_aboutBtn, 0);
    lv_obj_set_y(ui_aboutBtn, 220);
    lv_obj_add_flag(ui_aboutBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_aboutBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_aboutBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color4);
    ui_object_set_themeable_style_property(ui_aboutBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color4);

    ui_aboutBtnTxt = lv_label_create(ui_aboutBtn);
    lv_obj_set_width(ui_aboutBtnTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aboutBtnTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aboutBtnTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aboutBtnTxt, "About");
    ui_object_set_themeable_style_property(ui_aboutBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_aboutBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);

    ui_settingCloseBtn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_settingCloseBtn, 50);
    lv_obj_set_height(ui_settingCloseBtn, 50);
    lv_obj_set_x(ui_settingCloseBtn, -50);
    lv_obj_set_y(ui_settingCloseBtn, 20);
    lv_obj_set_align(ui_settingCloseBtn, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_settingCloseBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settingCloseBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_settingCloseBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_settingCloseBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_bg_img_src(ui_settingCloseBtn, &ui_img_setting_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_settingCloseBtn, lv_color_hex(0xF9F9FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_settingCloseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_settingCloseBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_settingCloseBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color1);

    ui_settingBtn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_settingBtn, 50);
    lv_obj_set_height(ui_settingBtn, 50);
    lv_obj_set_x(ui_settingBtn, -50);
    lv_obj_set_y(ui_settingBtn, 20);
    lv_obj_set_align(ui_settingBtn, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_settingBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settingBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_settingBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color5);
    ui_object_set_themeable_style_property(ui_settingBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color5);
    lv_obj_set_style_bg_img_src(ui_settingBtn, &ui_img_setting_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_settingBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_settingBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_color1);

    ui_MachineBtn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_MachineBtn, 200);
    lv_obj_set_height(ui_MachineBtn, 267);
    lv_obj_set_x(ui_MachineBtn, 40);
    lv_obj_set_y(ui_MachineBtn, 0);
    lv_obj_set_align(ui_MachineBtn, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MachineBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MachineBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_MachineBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color4);
    ui_object_set_themeable_style_property(ui_MachineBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color4);

    ui_machineBtnIcn = lv_img_create(ui_MachineBtn);
    lv_img_set_src(ui_machineBtnIcn, &ui_img_machine2_png);
    lv_obj_set_width(ui_machineBtnIcn, 150);
    lv_obj_set_height(ui_machineBtnIcn, 113);
    lv_obj_set_x(ui_machineBtnIcn, 0);
    lv_obj_set_y(ui_machineBtnIcn, 40);
    lv_obj_set_align(ui_machineBtnIcn, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_machineBtnIcn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_machineBtnIcn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_machineBtnTxt = lv_label_create(ui_MachineBtn);
    lv_obj_set_width(ui_machineBtnTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_machineBtnTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_machineBtnTxt, 0);
    lv_obj_set_y(ui_machineBtnTxt, -30);
    lv_obj_set_align(ui_machineBtnTxt, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_machineBtnTxt, "Machine 1");
    ui_object_set_themeable_style_property(ui_machineBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_machineBtnTxt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_text_align(ui_machineBtnTxt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_machineBtnTxt, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_opListBtn1, ui_event_opListBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_addUsrBtn1, ui_event_addUsrBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiCnfgbtn, ui_event_wifiCnfgbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_aboutBtn, ui_event_aboutBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingCloseBtn, ui_event_settingCloseBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingBtn, ui_event_settingBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MachineBtn, ui_event_MachineBtn, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_settingPnl2 = NULL;
    ui_opListBtn1 = NULL;
    ui_opListTxt1 = NULL;
    ui_addUsrBtn1 = NULL;
    ui_addUsrTxt1 = NULL;
    ui_wifiCnfgbtn = NULL;
    ui_wifiCnfgTxt = NULL;
    ui_aboutBtn = NULL;
    ui_aboutBtnTxt = NULL;
    ui_settingCloseBtn = NULL;
    ui_settingBtn = NULL;
    ui_MachineBtn = NULL;
    ui_machineBtnIcn = NULL;
    ui_machineBtnTxt = NULL;

}
