// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_AboutPnl = NULL;
lv_obj_t * ui_aboutWndw = NULL;
lv_obj_t * ui_aboutTitle = NULL;
lv_obj_t * ui_displayName = NULL;
lv_obj_t * ui_displayName1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Screen3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_AboutPnl = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_AboutPnl, 692);
    lv_obj_set_height(ui_AboutPnl, 400);
    lv_obj_set_x(ui_AboutPnl, 0);
    lv_obj_set_y(ui_AboutPnl, -30);
    lv_obj_set_align(ui_AboutPnl, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_AboutPnl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_AboutPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_AboutPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);
    ui_object_set_themeable_style_property(ui_AboutPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_AboutPnl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_color1);
    lv_obj_set_style_border_width(ui_AboutPnl, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aboutWndw = lv_obj_create(ui_AboutPnl);
    lv_obj_set_width(ui_aboutWndw, 522);
    lv_obj_set_height(ui_aboutWndw, 300);
    lv_obj_set_align(ui_aboutWndw, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_aboutWndw, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_aboutWndw, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color3);
    ui_object_set_themeable_style_property(ui_aboutWndw, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color3);
    lv_obj_set_style_border_width(ui_aboutWndw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aboutTitle = lv_label_create(ui_aboutWndw);
    lv_obj_set_width(ui_aboutTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aboutTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aboutTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_aboutTitle, "About");
    ui_object_set_themeable_style_property(ui_aboutTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color5);
    ui_object_set_themeable_style_property(ui_aboutTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color5);
    lv_obj_set_style_text_align(ui_aboutTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aboutTitle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_displayName = lv_label_create(ui_aboutWndw);
    lv_obj_set_width(ui_displayName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_displayName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_displayName, 0);
    lv_obj_set_y(ui_displayName, 50);
    lv_label_set_text(ui_displayName, "Display: Waveshare ESP32S3 Rouch LCD 7");
    lv_obj_set_style_text_color(ui_displayName, lv_color_hex(0xFBFBFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_displayName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_displayName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_displayName, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_displayName1 = lv_label_create(ui_aboutWndw);
    lv_obj_set_width(ui_displayName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_displayName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_displayName1, 0);
    lv_obj_set_y(ui_displayName1, 80);
    lv_label_set_text(ui_displayName1, "LVGL version: v8.3.11");
    lv_obj_set_style_text_color(ui_displayName1, lv_color_hex(0xFBFBFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_displayName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_displayName1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_displayName1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_AboutPnl);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 33);
    lv_obj_set_align(ui_Button1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color4);
    ui_object_set_themeable_style_property(ui_Button1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color4);

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Back");
    ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_color1);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_AboutPnl = NULL;
    ui_aboutWndw = NULL;
    ui_aboutTitle = NULL;
    ui_displayName = NULL;
    ui_displayName1 = NULL;
    ui_Button1 = NULL;
    ui_Label1 = NULL;

}
