// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#ifndef UI_SCREEN7_H
#define UI_SCREEN7_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen7
extern void ui_Screen7_screen_init(void);
extern void ui_Screen7_screen_destroy(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_TmprLable;
extern lv_obj_t * ui_TmprValue;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_hmdtLable1;
extern lv_obj_t * ui_hmdtValue1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_hmdtLable2;
extern lv_obj_t * ui_hmdtValue2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_prsLable1;
extern lv_obj_t * ui_prsValue1;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_prsLable2;
extern lv_obj_t * ui_prsValue2;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_prsLable3;
extern lv_obj_t * ui_prsValue3;
extern void ui_event_BckBtn(lv_event_t * e);
extern lv_obj_t * ui_BckBtn;
extern lv_obj_t * ui_BckBtnTxt;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

