// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_settingPnl2;
extern void ui_event_opListBtn1(lv_event_t * e);
extern lv_obj_t * ui_opListBtn1;
extern lv_obj_t * ui_opListTxt1;
extern void ui_event_addUsrBtn1(lv_event_t * e);
extern lv_obj_t * ui_addUsrBtn1;
extern lv_obj_t * ui_addUsrTxt1;
extern void ui_event_wifiCnfgbtn(lv_event_t * e);
extern lv_obj_t * ui_wifiCnfgbtn;
extern lv_obj_t * ui_wifiCnfgTxt;
extern void ui_event_aboutBtn(lv_event_t * e);
extern lv_obj_t * ui_aboutBtn;
extern lv_obj_t * ui_aboutBtnTxt;
extern void ui_event_settingCloseBtn(lv_event_t * e);
extern lv_obj_t * ui_settingCloseBtn;
extern void ui_event_settingBtn(lv_event_t * e);
extern lv_obj_t * ui_settingBtn;
extern void ui_event_MachineBtn(lv_event_t * e);
extern lv_obj_t * ui_MachineBtn;
extern lv_obj_t * ui_machineBtnIcn;
extern lv_obj_t * ui_machineBtnTxt;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

