// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#include "../ui.h"

lv_obj_t * ui_Screen8 = NULL;
lv_obj_t * ui_errorMsg = NULL;
lv_obj_t * ui_lgnUsrnm = NULL;
lv_obj_t * ui_lgnPswd = NULL;
lv_obj_t * ui_lginSbmtBtn = NULL;
lv_obj_t * ui_lgnSbmtTxt = NULL;
lv_obj_t * ui_lgnKbrd = NULL;
// event funtions
void ui_event_lgnUsrnm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_lgnKbrd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_lgnKbrd,  ui_lgnUsrnm);
        _ui_flag_modify(ui_errorMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_basic_set_property(ui_lgnUsrnm, _UI_BASIC_PROPERTY_POSITION_X,  0);
        _ui_basic_set_property(ui_lgnUsrnm, _UI_BASIC_PROPERTY_POSITION_Y,  -188);
        _ui_basic_set_property(ui_lgnUsrnm, _UI_BASIC_PROPERTY_WIDTH,  750);
    }
}

void ui_event_lgnPswd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_lgnKbrd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_lgnPswd, _UI_BASIC_PROPERTY_POSITION_Y,  -188);
        _ui_keyboard_set_target(ui_lgnKbrd,  ui_lgnPswd);
        _ui_flag_modify(ui_errorMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_basic_set_property(ui_lgnPswd, _UI_BASIC_PROPERTY_WIDTH,  750);
        _ui_basic_set_property(ui_lgnPswd, _UI_BASIC_PROPERTY_POSITION_X,  0);
    }
}

void ui_event_lginSbmtBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        check_login(e);
    }
}

void ui_event_lgnKbrd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_lgnKbrd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_basic_set_property(ui_lgnPswd, _UI_BASIC_PROPERTY_POSITION_Y,  -115);
        _ui_basic_set_property(ui_lgnPswd, _UI_BASIC_PROPERTY_WIDTH,  360);
        _ui_basic_set_property(ui_lgnPswd, _UI_BASIC_PROPERTY_POSITION_X,  -20);
        _ui_basic_set_property(ui_lgnUsrnm, _UI_BASIC_PROPERTY_WIDTH,  360);
        _ui_basic_set_property(ui_lgnUsrnm, _UI_BASIC_PROPERTY_POSITION_Y,  -195);
        _ui_basic_set_property(ui_lgnUsrnm, _UI_BASIC_PROPERTY_POSITION_X,  -20);
    }
}

// build funtions

void ui_Screen8_screen_init(void)
{
    ui_Screen8 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen8, &ui_img_loginpage_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_opa(ui_Screen8, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_errorMsg = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_errorMsg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_errorMsg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_errorMsg, 201);
    lv_obj_set_y(ui_errorMsg, 140);
    lv_obj_set_align(ui_errorMsg, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_errorMsg, "Error: Incorrect username or password.");
    lv_obj_add_flag(ui_errorMsg, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_errorMsg, lv_color_hex(0xE7081A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_errorMsg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_errorMsg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lgnUsrnm = lv_textarea_create(ui_Screen8);
    lv_obj_set_width(ui_lgnUsrnm, 360);
    lv_obj_set_height(ui_lgnUsrnm, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_lgnUsrnm, -20);
    lv_obj_set_y(ui_lgnUsrnm, -195);
    lv_obj_set_align(ui_lgnUsrnm, LV_ALIGN_BOTTOM_MID);
    lv_textarea_set_max_length(ui_lgnUsrnm, 10);
    lv_textarea_set_placeholder_text(ui_lgnUsrnm, "1234567890");
    lv_textarea_set_one_line(ui_lgnUsrnm, true);
    lv_obj_clear_flag(ui_lgnUsrnm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lgnUsrnm, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lgnPswd = lv_textarea_create(ui_Screen8);
    lv_obj_set_width(ui_lgnPswd, 360);
    lv_obj_set_height(ui_lgnPswd, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_lgnPswd, -20);
    lv_obj_set_y(ui_lgnPswd, -115);
    lv_obj_set_align(ui_lgnPswd, LV_ALIGN_BOTTOM_MID);
    lv_textarea_set_max_length(ui_lgnPswd, 4);
    lv_textarea_set_placeholder_text(ui_lgnPswd, "( 4 digit pin )");
    lv_textarea_set_one_line(ui_lgnPswd, true);
    lv_obj_clear_flag(ui_lgnPswd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lgnPswd, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lginSbmtBtn = lv_btn_create(ui_Screen8);
    lv_obj_set_width(ui_lginSbmtBtn, 100);
    lv_obj_set_height(ui_lginSbmtBtn, 40);
    lv_obj_set_x(ui_lginSbmtBtn, 0);
    lv_obj_set_y(ui_lginSbmtBtn, -20);
    lv_obj_set_align(ui_lginSbmtBtn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_lginSbmtBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lginSbmtBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lginSbmtBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_lginSbmtBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_lginSbmtBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);
    ui_object_set_themeable_style_property(ui_lginSbmtBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_lginSbmtBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_color1);

    ui_lgnSbmtTxt = lv_label_create(ui_lginSbmtBtn);
    lv_obj_set_width(ui_lgnSbmtTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lgnSbmtTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lgnSbmtTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lgnSbmtTxt, "Submit");

    ui_lgnKbrd = lv_keyboard_create(ui_Screen8);
    lv_keyboard_set_mode(ui_lgnKbrd, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_lgnKbrd, 800);
    lv_obj_set_height(ui_lgnKbrd, 188);
    lv_obj_set_align(ui_lgnKbrd, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_lgnKbrd, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_object_set_themeable_style_property(ui_lgnKbrd, LV_PART_ITEMS | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color5);
    ui_object_set_themeable_style_property(ui_lgnKbrd, LV_PART_ITEMS | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color5);

    lv_obj_add_event_cb(ui_lgnUsrnm, ui_event_lgnUsrnm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lgnPswd, ui_event_lgnPswd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lginSbmtBtn, ui_event_lginSbmtBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lgnKbrd, ui_event_lgnKbrd, LV_EVENT_ALL, NULL);

}

void ui_Screen8_screen_destroy(void)
{
    if(ui_Screen8) lv_obj_del(ui_Screen8);

    // NULL screen variables
    ui_Screen8 = NULL;
    ui_errorMsg = NULL;
    ui_lgnUsrnm = NULL;
    ui_lgnPswd = NULL;
    ui_lginSbmtBtn = NULL;
    ui_lgnSbmtTxt = NULL;
    ui_lgnKbrd = NULL;

}
