// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#ifndef _ILMS_UI_H
#define _ILMS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"
#include "screens/ui_Screen7.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen5.h"
#include "screens/ui_Screen6.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen8.h"
#include "screens/ui_Screen9.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * welcom_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * settingPnl_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * settingClosePnl_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * stettingPnlStngClsBtn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * settingClsOrgn_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_cover_png);    // assets/Cover.png
LV_IMG_DECLARE(ui_img_tick_png);    // assets/tick.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_machine2_png);    // assets/machine2.png
LV_IMG_DECLARE(ui_img_loginpage_png);    // assets/loginPage.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
