// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void clr_usr_list(lv_event_t * e);
void usr_config(lv_event_t * e);
void clr_textArea(lv_event_t * e);
void check_login(lv_event_t * e);
void wifi_cnfg(lv_event_t * e);
struct user* add_user ( struct user *, char *, char *);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
