// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: MY_UI_EXAMPLE

#include <stdio.h>
#include <ctype.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "ui.h"
#include "esp_log.h"
#include "stdlib.h"
#include "my_table.h"           /* custom made c file that contains definations of functions related to table initialization */
#include "esp_wifi.h"

static char* TAG = "UI_EVENT";


/* admin configurations defined in main.c file */
extern char* gAdmin_name;
extern char* gAdmin_pswd;

/* wifi details */
extern uint8_t gWifi_ssid[24];
extern uint8_t gWifi_pass[24];

/* wifi_task task handle */
//extern TaskHandle_t gWifi_handle;

/* wifi_init function from main.c */
void wifi_init();
void mqtt_client_init();

extern TaskHandle_t gWifi_handle;

/* root node for the linked list of users */
struct user* root = NULL;

/* check whether the entered user already exist or not */
uint8_t check_exist ( char *new_user ) {

    struct user *temp = root;
    
    /* check for root node null error */
    if ( root == NULL ) {
        return -1;
    }

    while ( 1 ) {
        if ( !(strcmp(temp->name,new_user)) ) {
            return 1;
        }
        if ( temp->next != NULL ) {
            temp = temp->next;
        }
        else {
            return 0;
        }
    }
}

/* function to add node in user data linked list ( new node is being added at the end ) */
struct user* add_user ( struct user *head, char *ta_usr_value, char *ta_pswd_value) {

    struct user* temp = head;
    char * node_usr_value = NULL;           /* pointer to memory storing username */
    char * node_pswd_value = NULL;          /* pointer to memory storing password */

    /* if the node is root node */
    if ( head == NULL ) {
        if ( (head = (struct user *)malloc(sizeof(struct user))) == NULL ) {    /* assigning memory to a node of linked list */
            ESP_LOGD(TAG,"couldn't allocate dynamic memory");
            return head;
        }
        if ( (node_usr_value = (char *)malloc( sizeof(char) * strlen(ta_usr_value) )) == NULL ) {
            ESP_LOGD(TAG,"couldn't allocate dynamic memory");
            free(head);
            return NULL;
        }
        if ( (node_pswd_value = (char *)malloc( sizeof(char) * strlen(ta_pswd_value) )) == NULL ) {
            ESP_LOGD(TAG,"couldn't allocate dynamic memory");
            free(head);
            return NULL;
        }

        strcpy( node_usr_value, ta_usr_value );
        strcpy( node_pswd_value, ta_pswd_value );
        
        head->name = node_usr_value;
        head->pswd = node_pswd_value;
        head->next = NULL;
        return head;
    }

    /* finding for the last node of linked list */
    while ( temp->next != NULL ) {
        temp = temp->next;
    }
    /* creating new node in the end and storing username and password there */
    if ( (temp->next = (struct user *)malloc(sizeof(struct user))) == NULL ) {      /* assigning memory to new node of linked list */
        ESP_LOGD(TAG,"couldn't allocate dynamic memory");
        return head;
    }   
    temp = temp->next;
    if ( (node_usr_value = (char *)malloc( sizeof(char) * strlen(ta_usr_value) ))  == NULL) {       /* allocating memory to username string */
        ESP_LOGD(TAG,"couldn't allocate dynamic memory");
        free(temp->next);
        return head;
    }

    if ( (node_pswd_value = (char *)malloc( sizeof(char) * strlen(ta_pswd_value) ))  == NULL) {       /* allocating memory to password string */
        ESP_LOGD(TAG,"couldn't allocate dynamic memory");
        free(node_usr_value);
        free(temp->next);
        return head;
    }

    strcpy( node_usr_value, ta_usr_value );                             /* copying text area's input to allocated memory*/
    strcpy( node_pswd_value, ta_pswd_value );                           /* copying text area's input to allocated memory*/

    /* giving pointers to node */
    temp->name = node_usr_value; 
    temp->pswd = node_pswd_value;
    temp->next = NULL;

    return head;
}

/* function to clear text area widget */
void clr_textArea(lv_event_t * e)
{
	lv_textarea_set_text(ui_usrNmBx, "");
	lv_textarea_set_text(ui_pswdBx, "");
}

/* callback function for submit button of add user panel */
void usr_config(lv_event_t * e)
{
    uint8_t i = 0;                                                                      /* variable for iterating through both inputs */
    char *usrnm = (char *)lv_textarea_get_text(ui_usrNmBx);
    char *pswd =  (char *)lv_textarea_get_text(ui_pswdBx);

    /* handle empty input case */
    if ( *usrnm == '\0' || *pswd == '\0' ) {
        _ui_flag_modify(ui_BxEmptyMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);       /* shows empty input error message on screen */
        _ui_flag_modify(ui_lengthMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);       /* hides input length error message on screen */
        _ui_flag_modify(ui_invldIpMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);       /* hides invalid input error message on screen */
        _ui_flag_modify(ui_usrExstMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);       /* hides user exists error message on screen */
        /* empty text area for username and password */
        lv_textarea_set_text(ui_usrNmBx, "");
        lv_textarea_set_text(ui_pswdBx, "");
        return;
    }

    /* handle input length error */
    if ( strlen(usrnm) < 4 || strlen(pswd) < 4 ) {
        _ui_flag_modify(ui_lengthMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);       /* shows input length error message on screen */
        _ui_flag_modify(ui_BxEmptyMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);       /* hides empty input error message on screen */
        _ui_flag_modify(ui_invldIpMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);       /* hides invalid input error message on screen */
        _ui_flag_modify(ui_usrExstMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);       /* hides user exists error message on screen */
        /* empty text area for username and password */
        lv_textarea_set_text(ui_usrNmBx, "");
        lv_textarea_set_text(ui_pswdBx, "");
        return;
    }

    /* check for invalid input ( only numbers are alowd */
    while ( pswd[i] != '\0' ) {
        if ( !(isdigit((uint8_t)pswd[i++])) ) {
            _ui_flag_modify(ui_invldIpMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);       /* shows invalid input error message on screen */
            _ui_flag_modify(ui_lengthMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);       /* hides input length error message on screen */
            _ui_flag_modify(ui_usrExstMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);       /* hides user exists error message on screen */
            _ui_flag_modify(ui_BxEmptyMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);       /* hides empty input error message on screen */
            /* empty text area for username and password */
            lv_textarea_set_text(ui_usrNmBx, "");
            lv_textarea_set_text(ui_pswdBx, "");
            return;
        }
    }
    i = 0;
    while ( usrnm[i] != '\0' ) {
        if ( !(isdigit((uint8_t)usrnm[i++])) ) {
            _ui_flag_modify(ui_invldIpMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);       /* shows invalid input error message on screen */
            _ui_flag_modify(ui_lengthMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);       /* hides input length error message on screen */
            _ui_flag_modify(ui_usrExstMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);       /* hides user exists error message on screen */
            _ui_flag_modify(ui_BxEmptyMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);       /* hides empty input error message on screen */
            /* empty text area for username and password */
            lv_textarea_set_text(ui_usrNmBx, "");
            lv_textarea_set_text(ui_pswdBx, "");
            return;
        }
    }

    /* check whether user already exist or not */
    if (root != NULL && check_exist(usrnm) ) {
        _ui_flag_modify(ui_usrExstMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);       /* shows user exists error message on screen */
        _ui_flag_modify(ui_lengthMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);           /* hides input length error message on screen */
        _ui_flag_modify(ui_BxEmptyMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);          /* hides empty input error message on screen */
        _ui_flag_modify(ui_invldIpMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);          /* hides invalid input error message on screen */
        /* empty text area for username and password */
        lv_textarea_set_text(ui_usrNmBx, "");
        lv_textarea_set_text(ui_pswdBx, "");
        return;
    }

    /* add user */
    root = add_user (root, usrnm, pswd);
    /* empty text area for username and password */
    lv_textarea_set_text(ui_usrNmBx, "");
    lv_textarea_set_text(ui_pswdBx, "");
    if ( root != NULL ) {
        update_table();
    }
    _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 0, &ui_Screen6_screen_init);


}

/* callback function for login page submit button */
void check_login(lv_event_t * e)
{
    //-------------    for testing purpose ---------------------------------------------------------
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 0, &ui_Screen2_screen_init);
    //----------------------------------------------------------------------------------------------
#if 0
    /* match username and password */
    if ( !strcmp((char *)lv_textarea_get_text(ui_lgnUsrnm),gAdmin_name) && !strcmp((char *)lv_textarea_get_text(ui_lgnPswd),gAdmin_pswd) ) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 0, &ui_Screen2_screen_init);
    }
    else {
        _ui_flag_modify(ui_errorMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);       /* shows error message on screen */
        lv_textarea_set_text(ui_lgnUsrnm, "");
        lv_textarea_set_text(ui_lgnPswd, "");
    }
#endif
}

/* callback function for clear user list button on operator list panel */
void clr_usr_list(lv_event_t * e)
{
    /* return from function if linked list is already empty */
    if ( root == NULL ) {
        return;
    }
    delete_users(root);

    /* a temporary variable for traveling between nodes */
    struct user* temp = root;
    
    /* iteratively free last node inside list */
    while ( root->next != NULL ) {
        temp = root;
        while ( temp->next->next != NULL ) {
            temp = temp->next;
        }
        free(temp->next);
        temp->next = NULL;
    }
    free(root);
    root = NULL;

    /* function that clears all data inside table of operator list table */
    clr_table(ui_table);
}

void wifi_cnfg(lv_event_t * e)
{
    const char* ssid = lv_textarea_get_text(ui_wifiSSIDBx);
    const char* pass = lv_textarea_get_text(ui_wifiPswdBx);

    memcpy(gWifi_ssid, ssid,strlen(ssid) + 1);
    memcpy(gWifi_pass, pass,strlen(pass) + 1);

    wifi_config_t wifi_data = {0};

    memcpy(wifi_data.sta.ssid, gWifi_ssid,strlen((char*)gWifi_ssid)+1);
    memcpy(wifi_data.sta.password, gWifi_pass,strlen((char*)gWifi_pass)+1);

    printf("new_ssid=%s\n",wifi_data.sta.ssid);
    printf("new_pswd=%s\n",wifi_data.sta.password);

    if(mqtt_client!=NULL){
        esp_mqtt_client_stop(mqtt_client);
    }

    esp_wifi_disconnect();
    vTaskDelay(1000/portTICK_PERIOD_MS);
    esp_wifi_stop();
    vTaskDelay(1000/portTICK_PERIOD_MS);
    
    esp_wifi_set_mode(WIFI_MODE_STA);
    esp_wifi_set_config(WIFI_IF_STA, &wifi_data);//sets the wifi data configuration
    esp_wifi_start();
    vTaskDelay(1000/portTICK_PERIOD_MS);
    esp_wifi_connect();//connect wifi station to AP

    lv_textarea_set_text(ui_wifiSSIDBx, "");
    lv_textarea_set_text(ui_wifiPswdBx, "");

    //wifi_init();
    //vTaskDelay(1000);
    //vTaskResume(gWifi_handle);
}
