// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ILMS

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_color1[1] = {0x001D39};
const ui_theme_variable_t _ui_theme_alpha_color1[1] = {255};

const ui_theme_variable_t _ui_theme_color_color2[1] = {0x0A4174};
const ui_theme_variable_t _ui_theme_alpha_color2[1] = {255};

const ui_theme_variable_t _ui_theme_color_color3[1] = {0x4E8EA2};
const ui_theme_variable_t _ui_theme_alpha_color3[1] = {255};

const ui_theme_variable_t _ui_theme_color_color4[1] = {0x7BBDE8};
const ui_theme_variable_t _ui_theme_alpha_color4[1] = {255};

const ui_theme_variable_t _ui_theme_color_color5[1] = {0xBDD8E9};
const ui_theme_variable_t _ui_theme_alpha_color5[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

